// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contactos.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const actualizarContacto = `-- name: ActualizarContacto :one
UPDATE contacto
SET nombre = $2,
    empresa = $3,
    correo = $4,
    pais = $5,
    campos_extra = $6,
    actualizado_en = now()
WHERE id = $1
RETURNING id, nombre, empresa, correo, pais, campos_extra, creado_en, actualizado_en
`

type ActualizarContactoParams struct {
	ID          uuid.UUID `json:"id"`
	Nombre      string    `json:"nombre"`
	Empresa     string    `json:"empresa"`
	Correo      string    `json:"correo"`
	Pais        *string   `json:"pais"`
	CamposExtra []byte    `json:"campos_extra"`
}

func (q *Queries) ActualizarContacto(ctx context.Context, arg ActualizarContactoParams) (Contacto, error) {
	row := q.db.QueryRow(ctx, actualizarContacto,
		arg.ID,
		arg.Nombre,
		arg.Empresa,
		arg.Correo,
		arg.Pais,
		arg.CamposExtra,
	)
	var i Contacto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Empresa,
		&i.Correo,
		&i.Pais,
		&i.CamposExtra,
		&i.CreadoEn,
		&i.ActualizadoEn,
	)
	return i, err
}

const contarContactos = `-- name: ContarContactos :one
SELECT count(*) FROM contacto
WHERE ($1::text IS NULL
   OR nombre ILIKE '%' || $1::text || '%'
   OR empresa ILIKE '%' || $1::text || '%'
   OR correo ILIKE '%' || $1::text || '%')
`

func (q *Queries) ContarContactos(ctx context.Context, busqueda *string) (int64, error) {
	row := q.db.QueryRow(ctx, contarContactos, busqueda)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearContacto = `-- name: CrearContacto :one
INSERT INTO contacto (nombre, empresa, correo, pais, campos_extra)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nombre, empresa, correo, pais, campos_extra, creado_en, actualizado_en
`

type CrearContactoParams struct {
	Nombre      string  `json:"nombre"`
	Empresa     string  `json:"empresa"`
	Correo      string  `json:"correo"`
	Pais        *string `json:"pais"`
	CamposExtra []byte  `json:"campos_extra"`
}

func (q *Queries) CrearContacto(ctx context.Context, arg CrearContactoParams) (Contacto, error) {
	row := q.db.QueryRow(ctx, crearContacto,
		arg.Nombre,
		arg.Empresa,
		arg.Correo,
		arg.Pais,
		arg.CamposExtra,
	)
	var i Contacto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Empresa,
		&i.Correo,
		&i.Pais,
		&i.CamposExtra,
		&i.CreadoEn,
		&i.ActualizadoEn,
	)
	return i, err
}

const eliminarContacto = `-- name: EliminarContacto :execrows
DELETE FROM contacto WHERE id = $1
`

func (q *Queries) EliminarContacto(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, eliminarContacto, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importarContacto = `-- name: ImportarContacto :one
INSERT INTO contacto (nombre, empresa, correo, pais, campos_extra)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (correo) DO UPDATE
SET nombre = EXCLUDED.nombre,
    empresa = EXCLUDED.empresa,
    pais = EXCLUDED.pais,
    campos_extra = contacto.campos_extra || EXCLUDED.campos_extra,
    actualizado_en = now()
RETURNING id, nombre, empresa, correo, pais, campos_extra, creado_en, actualizado_en, (xmax = 0) AS fue_creado
`

type ImportarContactoParams struct {
	Nombre      string  `json:"nombre"`
	Empresa     string  `json:"empresa"`
	Correo      string  `json:"correo"`
	Pais        *string `json:"pais"`
	CamposExtra []byte  `json:"campos_extra"`
}

type ImportarContactoRow struct {
	ID            uuid.UUID `json:"id"`
	Nombre        string    `json:"nombre"`
	Empresa       string    `json:"empresa"`
	Correo        string    `json:"correo"`
	Pais          *string   `json:"pais"`
	CamposExtra   []byte    `json:"campos_extra"`
	CreadoEn      time.Time `json:"creado_en"`
	ActualizadoEn time.Time `json:"actualizado_en"`
	FueCreado     bool      `json:"fue_creado"`
}

func (q *Queries) ImportarContacto(ctx context.Context, arg ImportarContactoParams) (ImportarContactoRow, error) {
	row := q.db.QueryRow(ctx, importarContacto,
		arg.Nombre,
		arg.Empresa,
		arg.Correo,
		arg.Pais,
		arg.CamposExtra,
	)
	var i ImportarContactoRow
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Empresa,
		&i.Correo,
		&i.Pais,
		&i.CamposExtra,
		&i.CreadoEn,
		&i.ActualizadoEn,
		&i.FueCreado,
	)
	return i, err
}

const listarContactos = `-- name: ListarContactos :many
SELECT id, nombre, empresa, correo, pais, campos_extra, creado_en, actualizado_en FROM contacto
WHERE ($3::text IS NULL
   OR nombre ILIKE '%' || $3::text || '%'
   OR empresa ILIKE '%' || $3::text || '%'
   OR correo ILIKE '%' || $3::text || '%')
ORDER BY creado_en DESC
LIMIT $1 OFFSET $2
`

type ListarContactosParams struct {
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
	Busqueda *string `json:"busqueda"`
}

func (q *Queries) ListarContactos(ctx context.Context, arg ListarContactosParams) ([]Contacto, error) {
	rows, err := q.db.Query(ctx, listarContactos, arg.Limit, arg.Offset, arg.Busqueda)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contacto{}
	for rows.Next() {
		var i Contacto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Empresa,
			&i.Correo,
			&i.Pais,
			&i.CamposExtra,
			&i.CreadoEn,
			&i.ActualizadoEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerContacto = `-- name: ObtenerContacto :one
SELECT id, nombre, empresa, correo, pais, campos_extra, creado_en, actualizado_en FROM contacto WHERE id = $1
`

func (q *Queries) ObtenerContacto(ctx context.Context, id uuid.UUID) (Contacto, error) {
	row := q.db.QueryRow(ctx, obtenerContacto, id)
	var i Contacto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Empresa,
		&i.Correo,
		&i.Pais,
		&i.CamposExtra,
		&i.CreadoEn,
		&i.ActualizadoEn,
	)
	return i, err
}

const obtenerContactoPorCorreo = `-- name: ObtenerContactoPorCorreo :one
SELECT id, nombre, empresa, correo, pais, campos_extra, creado_en, actualizado_en FROM contacto WHERE correo = $1
`

func (q *Queries) ObtenerContactoPorCorreo(ctx context.Context, correo string) (Contacto, error) {
	row := q.db.QueryRow(ctx, obtenerContactoPorCorreo, correo)
	var i Contacto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Empresa,
		&i.Correo,
		&i.Pais,
		&i.CamposExtra,
		&i.CreadoEn,
		&i.ActualizadoEn,
	)
	return i, err
}
