// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: correspondencia.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const actualizarCorrespondencia = `-- name: ActualizarCorrespondencia :one
UPDATE correspondencia
SET lista_id = $2,
    asunto = $3,
    cuerpo = $4,
    actualizado_en = now()
WHERE id = $1 AND estado = 'borrador'
RETURNING id, usuario_id, lista_id, asunto, cuerpo, estado, creado_en, actualizado_en
`

type ActualizarCorrespondenciaParams struct {
	ID      uuid.UUID  `json:"id"`
	ListaID *uuid.UUID `json:"lista_id"`
	Asunto  string     `json:"asunto"`
	Cuerpo  string     `json:"cuerpo"`
}

func (q *Queries) ActualizarCorrespondencia(ctx context.Context, arg ActualizarCorrespondenciaParams) (Correspondencia, error) {
	row := q.db.QueryRow(ctx, actualizarCorrespondencia,
		arg.ID,
		arg.ListaID,
		arg.Asunto,
		arg.Cuerpo,
	)
	var i Correspondencia
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.ListaID,
		&i.Asunto,
		&i.Cuerpo,
		&i.Estado,
		&i.CreadoEn,
		&i.ActualizadoEn,
	)
	return i, err
}

const cambiarEstadoCorrespondencia = `-- name: CambiarEstadoCorrespondencia :one
UPDATE correspondencia
SET estado = $2,
    actualizado_en = now()
WHERE id = $1
RETURNING id, usuario_id, lista_id, asunto, cuerpo, estado, creado_en, actualizado_en
`

type CambiarEstadoCorrespondenciaParams struct {
	ID     uuid.UUID `json:"id"`
	Estado string    `json:"estado"`
}

func (q *Queries) CambiarEstadoCorrespondencia(ctx context.Context, arg CambiarEstadoCorrespondenciaParams) (Correspondencia, error) {
	row := q.db.QueryRow(ctx, cambiarEstadoCorrespondencia, arg.ID, arg.Estado)
	var i Correspondencia
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.ListaID,
		&i.Asunto,
		&i.Cuerpo,
		&i.Estado,
		&i.CreadoEn,
		&i.ActualizadoEn,
	)
	return i, err
}

const contarCorrespondencia = `-- name: ContarCorrespondencia :one
SELECT count(*) FROM correspondencia
WHERE ($1::text IS NULL OR estado = $1::text)
`

func (q *Queries) ContarCorrespondencia(ctx context.Context, estado *string) (int64, error) {
	row := q.db.QueryRow(ctx, contarCorrespondencia, estado)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearAdjunto = `-- name: CrearAdjunto :one
INSERT INTO adjunto (correspondencia_id, nombre_archivo, url_archivo, tipo, tamano_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, correspondencia_id, nombre_archivo, url_archivo, tipo, tamano_bytes, creado_en
`

type CrearAdjuntoParams struct {
	CorrespondenciaID uuid.UUID `json:"correspondencia_id"`
	NombreArchivo     string    `json:"nombre_archivo"`
	UrlArchivo        string    `json:"url_archivo"`
	Tipo              string    `json:"tipo"`
	TamanoBytes       int64     `json:"tamano_bytes"`
}

func (q *Queries) CrearAdjunto(ctx context.Context, arg CrearAdjuntoParams) (Adjunto, error) {
	row := q.db.QueryRow(ctx, crearAdjunto,
		arg.CorrespondenciaID,
		arg.NombreArchivo,
		arg.UrlArchivo,
		arg.Tipo,
		arg.TamanoBytes,
	)
	var i Adjunto
	err := row.Scan(
		&i.ID,
		&i.CorrespondenciaID,
		&i.NombreArchivo,
		&i.UrlArchivo,
		&i.Tipo,
		&i.TamanoBytes,
		&i.CreadoEn,
	)
	return i, err
}

const crearCorrespondencia = `-- name: CrearCorrespondencia :one
INSERT INTO correspondencia (usuario_id, lista_id, asunto, cuerpo)
VALUES ($1, $2, $3, $4)
RETURNING id, usuario_id, lista_id, asunto, cuerpo, estado, creado_en, actualizado_en
`

type CrearCorrespondenciaParams struct {
	UsuarioID uuid.UUID  `json:"usuario_id"`
	ListaID   *uuid.UUID `json:"lista_id"`
	Asunto    string     `json:"asunto"`
	Cuerpo    string     `json:"cuerpo"`
}

func (q *Queries) CrearCorrespondencia(ctx context.Context, arg CrearCorrespondenciaParams) (Correspondencia, error) {
	row := q.db.QueryRow(ctx, crearCorrespondencia,
		arg.UsuarioID,
		arg.ListaID,
		arg.Asunto,
		arg.Cuerpo,
	)
	var i Correspondencia
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.ListaID,
		&i.Asunto,
		&i.Cuerpo,
		&i.Estado,
		&i.CreadoEn,
		&i.ActualizadoEn,
	)
	return i, err
}

const eliminarAdjunto = `-- name: EliminarAdjunto :execrows
DELETE FROM adjunto WHERE id = $1 AND correspondencia_id = $2
`

type EliminarAdjuntoParams struct {
	ID                uuid.UUID `json:"id"`
	CorrespondenciaID uuid.UUID `json:"correspondencia_id"`
}

func (q *Queries) EliminarAdjunto(ctx context.Context, arg EliminarAdjuntoParams) (int64, error) {
	result, err := q.db.Exec(ctx, eliminarAdjunto, arg.ID, arg.CorrespondenciaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eliminarCorrespondencia = `-- name: EliminarCorrespondencia :execrows
DELETE FROM correspondencia WHERE id = $1 AND estado = 'borrador'
`

func (q *Queries) EliminarCorrespondencia(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, eliminarCorrespondencia, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarAdjuntos = `-- name: ListarAdjuntos :many
SELECT id, correspondencia_id, nombre_archivo, url_archivo, tipo, tamano_bytes, creado_en FROM adjunto WHERE correspondencia_id = $1 ORDER BY creado_en
`

func (q *Queries) ListarAdjuntos(ctx context.Context, correspondenciaID uuid.UUID) ([]Adjunto, error) {
	rows, err := q.db.Query(ctx, listarAdjuntos, correspondenciaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Adjunto{}
	for rows.Next() {
		var i Adjunto
		if err := rows.Scan(
			&i.ID,
			&i.CorrespondenciaID,
			&i.NombreArchivo,
			&i.UrlArchivo,
			&i.Tipo,
			&i.TamanoBytes,
			&i.CreadoEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarCorrespondencia = `-- name: ListarCorrespondencia :many
SELECT id, usuario_id, lista_id, asunto, cuerpo, estado, creado_en, actualizado_en FROM correspondencia
WHERE ($3::text IS NULL OR estado = $3::text)
ORDER BY creado_en DESC
LIMIT $1 OFFSET $2
`

type ListarCorrespondenciaParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Estado *string `json:"estado"`
}

func (q *Queries) ListarCorrespondencia(ctx context.Context, arg ListarCorrespondenciaParams) ([]Correspondencia, error) {
	rows, err := q.db.Query(ctx, listarCorrespondencia, arg.Limit, arg.Offset, arg.Estado)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Correspondencia{}
	for rows.Next() {
		var i Correspondencia
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.ListaID,
			&i.Asunto,
			&i.Cuerpo,
			&i.Estado,
			&i.CreadoEn,
			&i.ActualizadoEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerAdjunto = `-- name: ObtenerAdjunto :one
SELECT id, correspondencia_id, nombre_archivo, url_archivo, tipo, tamano_bytes, creado_en FROM adjunto WHERE id = $1 AND correspondencia_id = $2
`

type ObtenerAdjuntoParams struct {
	ID                uuid.UUID `json:"id"`
	CorrespondenciaID uuid.UUID `json:"correspondencia_id"`
}

func (q *Queries) ObtenerAdjunto(ctx context.Context, arg ObtenerAdjuntoParams) (Adjunto, error) {
	row := q.db.QueryRow(ctx, obtenerAdjunto, arg.ID, arg.CorrespondenciaID)
	var i Adjunto
	err := row.Scan(
		&i.ID,
		&i.CorrespondenciaID,
		&i.NombreArchivo,
		&i.UrlArchivo,
		&i.Tipo,
		&i.TamanoBytes,
		&i.CreadoEn,
	)
	return i, err
}

const obtenerCorrespondencia = `-- name: ObtenerCorrespondencia :one
SELECT id, usuario_id, lista_id, asunto, cuerpo, estado, creado_en, actualizado_en FROM correspondencia WHERE id = $1
`

func (q *Queries) ObtenerCorrespondencia(ctx context.Context, id uuid.UUID) (Correspondencia, error) {
	row := q.db.QueryRow(ctx, obtenerCorrespondencia, id)
	var i Correspondencia
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.ListaID,
		&i.Asunto,
		&i.Cuerpo,
		&i.Estado,
		&i.CreadoEn,
		&i.ActualizadoEn,
	)
	return i, err
}

const obtenerPrimerContactoDeLista = `-- name: ObtenerPrimerContactoDeLista :one
SELECT c.id, c.nombre, c.empresa, c.correo, c.pais, c.campos_extra, c.creado_en, c.actualizado_en
FROM contacto c
JOIN contacto_lista cl ON cl.contacto_id = c.id
WHERE cl.lista_id = $1
ORDER BY c.empresa, c.nombre
LIMIT 1
`

func (q *Queries) ObtenerPrimerContactoDeLista(ctx context.Context, listaID uuid.UUID) (Contacto, error) {
	row := q.db.QueryRow(ctx, obtenerPrimerContactoDeLista, listaID)
	var i Contacto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Empresa,
		&i.Correo,
		&i.Pais,
		&i.CamposExtra,
		&i.CreadoEn,
		&i.ActualizadoEn,
	)
	return i, err
}

const sumarTamanoAdjuntos = `-- name: SumarTamanoAdjuntos :one
SELECT coalesce(sum(tamano_bytes), 0)::bigint FROM adjunto WHERE correspondencia_id = $1
`

func (q *Queries) SumarTamanoAdjuntos(ctx context.Context, correspondenciaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumarTamanoAdjuntos, correspondenciaID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
