// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directorio.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const aprobarDirectorioEmpresa = `-- name: AprobarDirectorioEmpresa :one
UPDATE directorio_empresa
SET estado = 'aprobado',
    contacto_id = $2,
    motivo_rechazo = NULL,
    revisado_en = now()
WHERE id = $1
RETURNING id, nombre, ruc, correo, direccion, ciudad, telefono, celular, facebook, pagina_web, descripcion, logo_url, estado, motivo_rechazo, contacto_id, creado_en, revisado_en
`

type AprobarDirectorioEmpresaParams struct {
	ID         uuid.UUID  `json:"id"`
	ContactoID *uuid.UUID `json:"contacto_id"`
}

func (q *Queries) AprobarDirectorioEmpresa(ctx context.Context, arg AprobarDirectorioEmpresaParams) (DirectorioEmpresa, error) {
	row := q.db.QueryRow(ctx, aprobarDirectorioEmpresa, arg.ID, arg.ContactoID)
	var i DirectorioEmpresa
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Ruc,
		&i.Correo,
		&i.Direccion,
		&i.Ciudad,
		&i.Telefono,
		&i.Celular,
		&i.Facebook,
		&i.PaginaWeb,
		&i.Descripcion,
		&i.LogoUrl,
		&i.Estado,
		&i.MotivoRechazo,
		&i.ContactoID,
		&i.CreadoEn,
		&i.RevisadoEn,
	)
	return i, err
}

const contarDirectorio = `-- name: ContarDirectorio :one
SELECT count(*) FROM directorio_empresa
WHERE ($1::text IS NULL OR estado = $1::text)
`

func (q *Queries) ContarDirectorio(ctx context.Context, estado *string) (int64, error) {
	row := q.db.QueryRow(ctx, contarDirectorio, estado)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearDirectorioEmpresa = `-- name: CrearDirectorioEmpresa :one
INSERT INTO directorio_empresa (
    nombre, ruc, correo, direccion, ciudad, telefono, celular,
    facebook, pagina_web, descripcion, logo_url
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, nombre, ruc, correo, direccion, ciudad, telefono, celular, facebook, pagina_web, descripcion, logo_url, estado, motivo_rechazo, contacto_id, creado_en, revisado_en
`

type CrearDirectorioEmpresaParams struct {
	Nombre      string  `json:"nombre"`
	Ruc         string  `json:"ruc"`
	Correo      string  `json:"correo"`
	Direccion   string  `json:"direccion"`
	Ciudad      string  `json:"ciudad"`
	Telefono    *string `json:"telefono"`
	Celular     *string `json:"celular"`
	Facebook    *string `json:"facebook"`
	PaginaWeb   *string `json:"pagina_web"`
	Descripcion string  `json:"descripcion"`
	LogoUrl     *string `json:"logo_url"`
}

func (q *Queries) CrearDirectorioEmpresa(ctx context.Context, arg CrearDirectorioEmpresaParams) (DirectorioEmpresa, error) {
	row := q.db.QueryRow(ctx, crearDirectorioEmpresa,
		arg.Nombre,
		arg.Ruc,
		arg.Correo,
		arg.Direccion,
		arg.Ciudad,
		arg.Telefono,
		arg.Celular,
		arg.Facebook,
		arg.PaginaWeb,
		arg.Descripcion,
		arg.LogoUrl,
	)
	var i DirectorioEmpresa
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Ruc,
		&i.Correo,
		&i.Direccion,
		&i.Ciudad,
		&i.Telefono,
		&i.Celular,
		&i.Facebook,
		&i.PaginaWeb,
		&i.Descripcion,
		&i.LogoUrl,
		&i.Estado,
		&i.MotivoRechazo,
		&i.ContactoID,
		&i.CreadoEn,
		&i.RevisadoEn,
	)
	return i, err
}

const listarDirectorio = `-- name: ListarDirectorio :many
SELECT id, nombre, ruc, correo, direccion, ciudad, telefono, celular, facebook, pagina_web, descripcion, logo_url, estado, motivo_rechazo, contacto_id, creado_en, revisado_en FROM directorio_empresa
WHERE ($3::text IS NULL OR estado = $3::text)
ORDER BY creado_en DESC
LIMIT $1 OFFSET $2
`

type ListarDirectorioParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Estado *string `json:"estado"`
}

func (q *Queries) ListarDirectorio(ctx context.Context, arg ListarDirectorioParams) ([]DirectorioEmpresa, error) {
	rows, err := q.db.Query(ctx, listarDirectorio, arg.Limit, arg.Offset, arg.Estado)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectorioEmpresa{}
	for rows.Next() {
		var i DirectorioEmpresa
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Ruc,
			&i.Correo,
			&i.Direccion,
			&i.Ciudad,
			&i.Telefono,
			&i.Celular,
			&i.Facebook,
			&i.PaginaWeb,
			&i.Descripcion,
			&i.LogoUrl,
			&i.Estado,
			&i.MotivoRechazo,
			&i.ContactoID,
			&i.CreadoEn,
			&i.RevisadoEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarDirectorioPublico = `-- name: ListarDirectorioPublico :many
SELECT id, nombre, ruc, correo, direccion, ciudad, telefono, celular, facebook, pagina_web, descripcion, logo_url, estado, motivo_rechazo, contacto_id, creado_en, revisado_en FROM directorio_empresa
WHERE estado = 'aprobado'
ORDER BY nombre
`

func (q *Queries) ListarDirectorioPublico(ctx context.Context) ([]DirectorioEmpresa, error) {
	rows, err := q.db.Query(ctx, listarDirectorioPublico)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectorioEmpresa{}
	for rows.Next() {
		var i DirectorioEmpresa
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Ruc,
			&i.Correo,
			&i.Direccion,
			&i.Ciudad,
			&i.Telefono,
			&i.Celular,
			&i.Facebook,
			&i.PaginaWeb,
			&i.Descripcion,
			&i.LogoUrl,
			&i.Estado,
			&i.MotivoRechazo,
			&i.ContactoID,
			&i.CreadoEn,
			&i.RevisadoEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerDirectorioEmpresa = `-- name: ObtenerDirectorioEmpresa :one
SELECT id, nombre, ruc, correo, direccion, ciudad, telefono, celular, facebook, pagina_web, descripcion, logo_url, estado, motivo_rechazo, contacto_id, creado_en, revisado_en FROM directorio_empresa WHERE id = $1
`

func (q *Queries) ObtenerDirectorioEmpresa(ctx context.Context, id uuid.UUID) (DirectorioEmpresa, error) {
	row := q.db.QueryRow(ctx, obtenerDirectorioEmpresa, id)
	var i DirectorioEmpresa
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Ruc,
		&i.Correo,
		&i.Direccion,
		&i.Ciudad,
		&i.Telefono,
		&i.Celular,
		&i.Facebook,
		&i.PaginaWeb,
		&i.Descripcion,
		&i.LogoUrl,
		&i.Estado,
		&i.MotivoRechazo,
		&i.ContactoID,
		&i.CreadoEn,
		&i.RevisadoEn,
	)
	return i, err
}

const obtenerListaPorNombre = `-- name: ObtenerListaPorNombre :one
SELECT id, nombre, descripcion, creado_en FROM lista_contactos WHERE nombre = $1 ORDER BY creado_en LIMIT 1
`

func (q *Queries) ObtenerListaPorNombre(ctx context.Context, nombre string) (ListaContacto, error) {
	row := q.db.QueryRow(ctx, obtenerListaPorNombre, nombre)
	var i ListaContacto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.CreadoEn,
	)
	return i, err
}

const rechazarDirectorioEmpresa = `-- name: RechazarDirectorioEmpresa :one
UPDATE directorio_empresa
SET estado = 'rechazado',
    motivo_rechazo = $2,
    revisado_en = now()
WHERE id = $1
RETURNING id, nombre, ruc, correo, direccion, ciudad, telefono, celular, facebook, pagina_web, descripcion, logo_url, estado, motivo_rechazo, contacto_id, creado_en, revisado_en
`

type RechazarDirectorioEmpresaParams struct {
	ID            uuid.UUID `json:"id"`
	MotivoRechazo *string   `json:"motivo_rechazo"`
}

func (q *Queries) RechazarDirectorioEmpresa(ctx context.Context, arg RechazarDirectorioEmpresaParams) (DirectorioEmpresa, error) {
	row := q.db.QueryRow(ctx, rechazarDirectorioEmpresa, arg.ID, arg.MotivoRechazo)
	var i DirectorioEmpresa
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Ruc,
		&i.Correo,
		&i.Direccion,
		&i.Ciudad,
		&i.Telefono,
		&i.Celular,
		&i.Facebook,
		&i.PaginaWeb,
		&i.Descripcion,
		&i.LogoUrl,
		&i.Estado,
		&i.MotivoRechazo,
		&i.ContactoID,
		&i.CreadoEn,
		&i.RevisadoEn,
	)
	return i, err
}
