// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: envios.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const actualizarEstadoPorMensaje = `-- name: ActualizarEstadoPorMensaje :one
UPDATE envio
SET estado = $2,
    actualizado_en = now()
WHERE proveedor_mensaje_id = $1
RETURNING id
`

type ActualizarEstadoPorMensajeParams struct {
	ProveedorMensajeID *string `json:"proveedor_mensaje_id"`
	Estado             string  `json:"estado"`
}

func (q *Queries) ActualizarEstadoPorMensaje(ctx context.Context, arg ActualizarEstadoPorMensajeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, actualizarEstadoPorMensaje, arg.ProveedorMensajeID, arg.Estado)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const cerrarCorrespondenciaSiTermino = `-- name: CerrarCorrespondenciaSiTermino :one
UPDATE correspondencia c
SET estado = CASE
        WHEN NOT EXISTS (
            SELECT 1 FROM envio e
            WHERE e.correspondencia_id = c.id AND e.estado <> 'fallido'
        ) THEN 'fallida'
        ELSE 'enviada'
    END,
    actualizado_en = now()
WHERE c.id = $1
  AND c.estado IN ('encolada', 'enviando')
  AND NOT EXISTS (
      SELECT 1 FROM envio e
      WHERE e.correspondencia_id = c.id AND e.estado = 'pendiente'
  )
RETURNING c.estado
`

func (q *Queries) CerrarCorrespondenciaSiTermino(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, cerrarCorrespondenciaSiTermino, id)
	var estado string
	err := row.Scan(&estado)
	return estado, err
}

const contarEnviosDeCorrespondencia = `-- name: ContarEnviosDeCorrespondencia :one
SELECT count(*) FROM envio
WHERE correspondencia_id = $1
  AND ($2::text IS NULL OR estado = $2::text)
`

type ContarEnviosDeCorrespondenciaParams struct {
	CorrespondenciaID uuid.UUID `json:"correspondencia_id"`
	Estado            *string   `json:"estado"`
}

func (q *Queries) ContarEnviosDeCorrespondencia(ctx context.Context, arg ContarEnviosDeCorrespondenciaParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarEnviosDeCorrespondencia, arg.CorrespondenciaID, arg.Estado)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarPendientesDeCorrespondencia = `-- name: ContarPendientesDeCorrespondencia :one
SELECT count(*) FROM envio
WHERE correspondencia_id = $1 AND estado = 'pendiente'
`

func (q *Queries) ContarPendientesDeCorrespondencia(ctx context.Context, correspondenciaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarPendientesDeCorrespondencia, correspondenciaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarSuprimidosDeLista = `-- name: ContarSuprimidosDeLista :one
SELECT count(*)
FROM contacto_lista cl
JOIN contacto c ON c.id = cl.contacto_id
JOIN supresion s ON s.correo = c.correo
WHERE cl.lista_id = $1
`

func (q *Queries) ContarSuprimidosDeLista(ctx context.Context, listaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarSuprimidosDeLista, listaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearEnviosDeLista = `-- name: CrearEnviosDeLista :execrows
INSERT INTO envio (correspondencia_id, contacto_id)
SELECT $1, cl.contacto_id
FROM contacto_lista cl
JOIN contacto c ON c.id = cl.contacto_id
WHERE cl.lista_id = $2
  AND NOT EXISTS (SELECT 1 FROM supresion s WHERE s.correo = c.correo)
ON CONFLICT (correspondencia_id, contacto_id) DO NOTHING
`

type CrearEnviosDeListaParams struct {
	CorrespondenciaID uuid.UUID `json:"correspondencia_id"`
	ListaID           uuid.UUID `json:"lista_id"`
}

func (q *Queries) CrearEnviosDeLista(ctx context.Context, arg CrearEnviosDeListaParams) (int64, error) {
	result, err := q.db.Exec(ctx, crearEnviosDeLista, arg.CorrespondenciaID, arg.ListaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarEnviosDeCorrespondencia = `-- name: ListarEnviosDeCorrespondencia :many
SELECT
    e.id,
    e.estado,
    e.proveedor_mensaje_id,
    e.fecha_envio,
    c.nombre,
    c.empresa,
    c.correo
FROM envio e
JOIN contacto c ON c.id = e.contacto_id
WHERE e.correspondencia_id = $1
  AND ($4::text IS NULL OR e.estado = $4::text)
ORDER BY c.empresa, c.nombre
LIMIT $2 OFFSET $3
`

type ListarEnviosDeCorrespondenciaParams struct {
	CorrespondenciaID uuid.UUID `json:"correspondencia_id"`
	Limit             int32     `json:"limit"`
	Offset            int32     `json:"offset"`
	Estado            *string   `json:"estado"`
}

type ListarEnviosDeCorrespondenciaRow struct {
	ID                 uuid.UUID  `json:"id"`
	Estado             string     `json:"estado"`
	ProveedorMensajeID *string    `json:"proveedor_mensaje_id"`
	FechaEnvio         *time.Time `json:"fecha_envio"`
	Nombre             string     `json:"nombre"`
	Empresa            string     `json:"empresa"`
	Correo             string     `json:"correo"`
}

func (q *Queries) ListarEnviosDeCorrespondencia(ctx context.Context, arg ListarEnviosDeCorrespondenciaParams) ([]ListarEnviosDeCorrespondenciaRow, error) {
	rows, err := q.db.Query(ctx, listarEnviosDeCorrespondencia,
		arg.CorrespondenciaID,
		arg.Limit,
		arg.Offset,
		arg.Estado,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarEnviosDeCorrespondenciaRow{}
	for rows.Next() {
		var i ListarEnviosDeCorrespondenciaRow
		if err := rows.Scan(
			&i.ID,
			&i.Estado,
			&i.ProveedorMensajeID,
			&i.FechaEnvio,
			&i.Nombre,
			&i.Empresa,
			&i.Correo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarEnviosPendientes = `-- name: ListarEnviosPendientes :many
SELECT e.id, e.correspondencia_id, e.contacto_id
FROM envio e
WHERE e.correspondencia_id = $1 AND e.estado = 'pendiente'
ORDER BY e.creado_en
`

type ListarEnviosPendientesRow struct {
	ID                uuid.UUID `json:"id"`
	CorrespondenciaID uuid.UUID `json:"correspondencia_id"`
	ContactoID        uuid.UUID `json:"contacto_id"`
}

func (q *Queries) ListarEnviosPendientes(ctx context.Context, correspondenciaID uuid.UUID) ([]ListarEnviosPendientesRow, error) {
	rows, err := q.db.Query(ctx, listarEnviosPendientes, correspondenciaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarEnviosPendientesRow{}
	for rows.Next() {
		var i ListarEnviosPendientesRow
		if err := rows.Scan(&i.ID, &i.CorrespondenciaID, &i.ContactoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarEventosDeEnvio = `-- name: ListarEventosDeEnvio :many
SELECT id, envio_id, tipo, fecha, payload, creado_en FROM evento_envio WHERE envio_id = $1 ORDER BY fecha DESC
`

func (q *Queries) ListarEventosDeEnvio(ctx context.Context, envioID uuid.UUID) ([]EventoEnvio, error) {
	rows, err := q.db.Query(ctx, listarEventosDeEnvio, envioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventoEnvio{}
	for rows.Next() {
		var i EventoEnvio
		if err := rows.Scan(
			&i.ID,
			&i.EnvioID,
			&i.Tipo,
			&i.Fecha,
			&i.Payload,
			&i.CreadoEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarEnvioEnviado = `-- name: MarcarEnvioEnviado :execrows
UPDATE envio
SET estado = 'enviado',
    proveedor_mensaje_id = $2,
    fecha_envio = now(),
    actualizado_en = now()
WHERE id = $1
`

type MarcarEnvioEnviadoParams struct {
	ID                 uuid.UUID `json:"id"`
	ProveedorMensajeID *string   `json:"proveedor_mensaje_id"`
}

func (q *Queries) MarcarEnvioEnviado(ctx context.Context, arg MarcarEnvioEnviadoParams) (int64, error) {
	result, err := q.db.Exec(ctx, marcarEnvioEnviado, arg.ID, arg.ProveedorMensajeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const marcarEnvioFallido = `-- name: MarcarEnvioFallido :execrows
UPDATE envio
SET estado = 'fallido',
    actualizado_en = now()
WHERE id = $1
`

func (q *Queries) MarcarEnvioFallido(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, marcarEnvioFallido, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const obtenerEnvioConDatos = `-- name: ObtenerEnvioConDatos :one
SELECT
    e.id,
    e.correspondencia_id,
    e.estado,
    c.id AS contacto_id,
    c.nombre,
    c.empresa,
    c.correo,
    c.pais,
    c.campos_extra,
    c.creado_en AS contacto_creado_en,
    c.actualizado_en AS contacto_actualizado_en
FROM envio e
JOIN contacto c ON c.id = e.contacto_id
WHERE e.id = $1
`

type ObtenerEnvioConDatosRow struct {
	ID                    uuid.UUID `json:"id"`
	CorrespondenciaID     uuid.UUID `json:"correspondencia_id"`
	Estado                string    `json:"estado"`
	ContactoID            uuid.UUID `json:"contacto_id"`
	Nombre                string    `json:"nombre"`
	Empresa               string    `json:"empresa"`
	Correo                string    `json:"correo"`
	Pais                  *string   `json:"pais"`
	CamposExtra           []byte    `json:"campos_extra"`
	ContactoCreadoEn      time.Time `json:"contacto_creado_en"`
	ContactoActualizadoEn time.Time `json:"contacto_actualizado_en"`
}

func (q *Queries) ObtenerEnvioConDatos(ctx context.Context, id uuid.UUID) (ObtenerEnvioConDatosRow, error) {
	row := q.db.QueryRow(ctx, obtenerEnvioConDatos, id)
	var i ObtenerEnvioConDatosRow
	err := row.Scan(
		&i.ID,
		&i.CorrespondenciaID,
		&i.Estado,
		&i.ContactoID,
		&i.Nombre,
		&i.Empresa,
		&i.Correo,
		&i.Pais,
		&i.CamposExtra,
		&i.ContactoCreadoEn,
		&i.ContactoActualizadoEn,
	)
	return i, err
}

const obtenerEnvioPorMensaje = `-- name: ObtenerEnvioPorMensaje :one
SELECT id FROM envio WHERE proveedor_mensaje_id = $1
`

func (q *Queries) ObtenerEnvioPorMensaje(ctx context.Context, proveedorMensajeID *string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, obtenerEnvioPorMensaje, proveedorMensajeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const registrarEventoEnvio = `-- name: RegistrarEventoEnvio :one
INSERT INTO evento_envio (envio_id, tipo, fecha, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, envio_id, tipo, fecha, payload, creado_en
`

type RegistrarEventoEnvioParams struct {
	EnvioID uuid.UUID `json:"envio_id"`
	Tipo    string    `json:"tipo"`
	Fecha   time.Time `json:"fecha"`
	Payload []byte    `json:"payload"`
}

func (q *Queries) RegistrarEventoEnvio(ctx context.Context, arg RegistrarEventoEnvioParams) (EventoEnvio, error) {
	row := q.db.QueryRow(ctx, registrarEventoEnvio,
		arg.EnvioID,
		arg.Tipo,
		arg.Fecha,
		arg.Payload,
	)
	var i EventoEnvio
	err := row.Scan(
		&i.ID,
		&i.EnvioID,
		&i.Tipo,
		&i.Fecha,
		&i.Payload,
		&i.CreadoEn,
	)
	return i, err
}

const resumenEnvios = `-- name: ResumenEnvios :many
SELECT estado, count(*) AS total
FROM envio
WHERE correspondencia_id = $1
GROUP BY estado
`

type ResumenEnviosRow struct {
	Estado string `json:"estado"`
	Total  int64  `json:"total"`
}

func (q *Queries) ResumenEnvios(ctx context.Context, correspondenciaID uuid.UUID) ([]ResumenEnviosRow, error) {
	rows, err := q.db.Query(ctx, resumenEnvios, correspondenciaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResumenEnviosRow{}
	for rows.Next() {
		var i ResumenEnviosRow
		if err := rows.Scan(&i.Estado, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
