// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listas.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const actualizarLista = `-- name: ActualizarLista :one
UPDATE lista_contactos
SET nombre = $2,
    descripcion = $3
WHERE id = $1
RETURNING id, nombre, descripcion, creado_en
`

type ActualizarListaParams struct {
	ID          uuid.UUID `json:"id"`
	Nombre      string    `json:"nombre"`
	Descripcion *string   `json:"descripcion"`
}

func (q *Queries) ActualizarLista(ctx context.Context, arg ActualizarListaParams) (ListaContacto, error) {
	row := q.db.QueryRow(ctx, actualizarLista, arg.ID, arg.Nombre, arg.Descripcion)
	var i ListaContacto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.CreadoEn,
	)
	return i, err
}

const agregarContactosALista = `-- name: AgregarContactosALista :execrows
INSERT INTO contacto_lista (lista_id, contacto_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type AgregarContactosAListaParams struct {
	ListaID     uuid.UUID   `json:"lista_id"`
	ContactoIds []uuid.UUID `json:"contacto_ids"`
}

func (q *Queries) AgregarContactosALista(ctx context.Context, arg AgregarContactosAListaParams) (int64, error) {
	result, err := q.db.Exec(ctx, agregarContactosALista, arg.ListaID, arg.ContactoIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const contarContactosDeLista = `-- name: ContarContactosDeLista :one
SELECT count(*) FROM contacto_lista WHERE lista_id = $1
`

func (q *Queries) ContarContactosDeLista(ctx context.Context, listaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarContactosDeLista, listaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarListas = `-- name: ContarListas :one
SELECT count(*) FROM lista_contactos
`

func (q *Queries) ContarListas(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarListas)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearLista = `-- name: CrearLista :one
INSERT INTO lista_contactos (nombre, descripcion)
VALUES ($1, $2)
RETURNING id, nombre, descripcion, creado_en
`

type CrearListaParams struct {
	Nombre      string  `json:"nombre"`
	Descripcion *string `json:"descripcion"`
}

func (q *Queries) CrearLista(ctx context.Context, arg CrearListaParams) (ListaContacto, error) {
	row := q.db.QueryRow(ctx, crearLista, arg.Nombre, arg.Descripcion)
	var i ListaContacto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.CreadoEn,
	)
	return i, err
}

const eliminarLista = `-- name: EliminarLista :execrows
DELETE FROM lista_contactos WHERE id = $1
`

func (q *Queries) EliminarLista(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, eliminarLista, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existeLista = `-- name: ExisteLista :one
SELECT EXISTS (SELECT 1 FROM lista_contactos WHERE id = $1)
`

func (q *Queries) ExisteLista(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existeLista, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listarContactosDeLista = `-- name: ListarContactosDeLista :many
SELECT c.id, c.nombre, c.empresa, c.correo, c.pais, c.campos_extra, c.creado_en, c.actualizado_en
FROM contacto c
JOIN contacto_lista cl ON cl.contacto_id = c.id
WHERE cl.lista_id = $1
ORDER BY c.empresa, c.nombre
LIMIT $2 OFFSET $3
`

type ListarContactosDeListaParams struct {
	ListaID uuid.UUID `json:"lista_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListarContactosDeLista(ctx context.Context, arg ListarContactosDeListaParams) ([]Contacto, error) {
	rows, err := q.db.Query(ctx, listarContactosDeLista, arg.ListaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contacto{}
	for rows.Next() {
		var i Contacto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Empresa,
			&i.Correo,
			&i.Pais,
			&i.CamposExtra,
			&i.CreadoEn,
			&i.ActualizadoEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarListas = `-- name: ListarListas :many
SELECT l.id, l.nombre, l.descripcion, l.creado_en, count(cl.contacto_id) AS total_contactos
FROM lista_contactos l
LEFT JOIN contacto_lista cl ON cl.lista_id = l.id
GROUP BY l.id
ORDER BY l.creado_en DESC
LIMIT $1 OFFSET $2
`

type ListarListasParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListarListasRow struct {
	ID             uuid.UUID `json:"id"`
	Nombre         string    `json:"nombre"`
	Descripcion    *string   `json:"descripcion"`
	CreadoEn       time.Time `json:"creado_en"`
	TotalContactos int64     `json:"total_contactos"`
}

func (q *Queries) ListarListas(ctx context.Context, arg ListarListasParams) ([]ListarListasRow, error) {
	rows, err := q.db.Query(ctx, listarListas, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarListasRow{}
	for rows.Next() {
		var i ListarListasRow
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.CreadoEn,
			&i.TotalContactos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerLista = `-- name: ObtenerLista :one
SELECT l.id, l.nombre, l.descripcion, l.creado_en, count(cl.contacto_id) AS total_contactos
FROM lista_contactos l
LEFT JOIN contacto_lista cl ON cl.lista_id = l.id
WHERE l.id = $1
GROUP BY l.id
`

type ObtenerListaRow struct {
	ID             uuid.UUID `json:"id"`
	Nombre         string    `json:"nombre"`
	Descripcion    *string   `json:"descripcion"`
	CreadoEn       time.Time `json:"creado_en"`
	TotalContactos int64     `json:"total_contactos"`
}

func (q *Queries) ObtenerLista(ctx context.Context, id uuid.UUID) (ObtenerListaRow, error) {
	row := q.db.QueryRow(ctx, obtenerLista, id)
	var i ObtenerListaRow
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.CreadoEn,
		&i.TotalContactos,
	)
	return i, err
}

const quitarContactoDeLista = `-- name: QuitarContactoDeLista :execrows
DELETE FROM contacto_lista WHERE lista_id = $1 AND contacto_id = $2
`

type QuitarContactoDeListaParams struct {
	ListaID    uuid.UUID `json:"lista_id"`
	ContactoID uuid.UUID `json:"contacto_id"`
}

func (q *Queries) QuitarContactoDeLista(ctx context.Context, arg QuitarContactoDeListaParams) (int64, error) {
	result, err := q.db.Exec(ctx, quitarContactoDeLista, arg.ListaID, arg.ContactoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
