// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Adjunto struct {
	ID                uuid.UUID `json:"id"`
	CorrespondenciaID uuid.UUID `json:"correspondencia_id"`
	NombreArchivo     string    `json:"nombre_archivo"`
	UrlArchivo        string    `json:"url_archivo"`
	Tipo              string    `json:"tipo"`
	TamanoBytes       int64     `json:"tamano_bytes"`
	CreadoEn          time.Time `json:"creado_en"`
}

type Contacto struct {
	ID            uuid.UUID `json:"id"`
	Nombre        string    `json:"nombre"`
	Empresa       string    `json:"empresa"`
	Correo        string    `json:"correo"`
	Pais          *string   `json:"pais"`
	CamposExtra   []byte    `json:"campos_extra"`
	CreadoEn      time.Time `json:"creado_en"`
	ActualizadoEn time.Time `json:"actualizado_en"`
}

type ContactoLista struct {
	ContactoID uuid.UUID `json:"contacto_id"`
	ListaID    uuid.UUID `json:"lista_id"`
	AgregadoEn time.Time `json:"agregado_en"`
}

type Correspondencia struct {
	ID              uuid.UUID  `json:"id"`
	UsuarioID       uuid.UUID  `json:"usuario_id"`
	ListaID         *uuid.UUID `json:"lista_id"`
	Asunto          string     `json:"asunto"`
	Cuerpo          string     `json:"cuerpo"`
	Estado          string     `json:"estado"`
	CreadoEn        time.Time  `json:"creado_en"`
	ActualizadoEn   time.Time  `json:"actualizado_en"`
	PlantillaUrl    *string    `json:"plantilla_url"`
	PlantillaNombre *string    `json:"plantilla_nombre"`
}

type DirectorioEmpresa struct {
	ID            uuid.UUID  `json:"id"`
	Nombre        string     `json:"nombre"`
	Ruc           string     `json:"ruc"`
	Correo        string     `json:"correo"`
	Direccion     string     `json:"direccion"`
	Ciudad        string     `json:"ciudad"`
	Telefono      *string    `json:"telefono"`
	Celular       *string    `json:"celular"`
	Facebook      *string    `json:"facebook"`
	PaginaWeb     *string    `json:"pagina_web"`
	Descripcion   string     `json:"descripcion"`
	LogoUrl       *string    `json:"logo_url"`
	Estado        string     `json:"estado"`
	MotivoRechazo *string    `json:"motivo_rechazo"`
	ContactoID    *uuid.UUID `json:"contacto_id"`
	CreadoEn      time.Time  `json:"creado_en"`
	RevisadoEn    *time.Time `json:"revisado_en"`
}

type Envio struct {
	ID                 uuid.UUID  `json:"id"`
	CorrespondenciaID  uuid.UUID  `json:"correspondencia_id"`
	ContactoID         uuid.UUID  `json:"contacto_id"`
	ProveedorMensajeID *string    `json:"proveedor_mensaje_id"`
	Estado             string     `json:"estado"`
	FechaEnvio         *time.Time `json:"fecha_envio"`
	CreadoEn           time.Time  `json:"creado_en"`
	ActualizadoEn      time.Time  `json:"actualizado_en"`
}

type EventoEnvio struct {
	ID       uuid.UUID `json:"id"`
	EnvioID  uuid.UUID `json:"envio_id"`
	Tipo     string    `json:"tipo"`
	Fecha    time.Time `json:"fecha"`
	Payload  []byte    `json:"payload"`
	CreadoEn time.Time `json:"creado_en"`
}

type ListaContacto struct {
	ID          uuid.UUID `json:"id"`
	Nombre      string    `json:"nombre"`
	Descripcion *string   `json:"descripcion"`
	CreadoEn    time.Time `json:"creado_en"`
}

type RuedaCoincidencia struct {
	ID           uuid.UUID  `json:"id"`
	DemandaID    uuid.UUID  `json:"demanda_id"`
	OfertaID     uuid.UUID  `json:"oferta_id"`
	Puntaje      int32      `json:"puntaje"`
	Motivo       string     `json:"motivo"`
	Estado       string     `json:"estado"`
	CreadoEn     time.Time  `json:"creado_en"`
	NotificadaEn *time.Time `json:"notificada_en"`
}

type RuedaEmpresa struct {
	ID               uuid.UUID  `json:"id"`
	RazonSocial      string     `json:"razon_social"`
	Ruc              string     `json:"ruc"`
	PersonaEncargada string     `json:"persona_encargada"`
	CargoEncargado   *string    `json:"cargo_encargado"`
	Correo           string     `json:"correo"`
	Direccion        *string    `json:"direccion"`
	Ciudad           *string    `json:"ciudad"`
	Region           *string    `json:"region"`
	Pais             string     `json:"pais"`
	CodigoPostal     *string    `json:"codigo_postal"`
	Telefono         *string    `json:"telefono"`
	Celular          *string    `json:"celular"`
	PaginaWeb        *string    `json:"pagina_web"`
	Estado           string     `json:"estado"`
	MotivoRechazo    *string    `json:"motivo_rechazo"`
	ContactoID       *uuid.UUID `json:"contacto_id"`
	CreadoEn         time.Time  `json:"creado_en"`
	RevisadoEn       *time.Time `json:"revisado_en"`
}

type RuedaPublicacion struct {
	ID            uuid.UUID  `json:"id"`
	EmpresaID     uuid.UUID  `json:"empresa_id"`
	Tipo          string     `json:"tipo"`
	Titulo        string     `json:"titulo"`
	Descripcion   string     `json:"descripcion"`
	ImagenUrl     *string    `json:"imagen_url"`
	Estado        string     `json:"estado"`
	MotivoRechazo *string    `json:"motivo_rechazo"`
	CreadoEn      time.Time  `json:"creado_en"`
	RevisadoEn    *time.Time `json:"revisado_en"`
}

type Supresion struct {
	Correo   string    `json:"correo"`
	Motivo   string    `json:"motivo"`
	Detalle  *string   `json:"detalle"`
	CreadoEn time.Time `json:"creado_en"`
}

type Usuario struct {
	ID           uuid.UUID `json:"id"`
	Nombre       string    `json:"nombre"`
	Correo       string    `json:"correo"`
	PasswordHash string    `json:"password_hash"`
	CreadoEn     time.Time `json:"creado_en"`
}
