// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Adjunto struct {
	ID                uuid.UUID `json:"id"`
	CorrespondenciaID uuid.UUID `json:"correspondencia_id"`
	NombreArchivo     string    `json:"nombre_archivo"`
	UrlArchivo        string    `json:"url_archivo"`
	Tipo              string    `json:"tipo"`
	TamanoBytes       int64     `json:"tamano_bytes"`
	CreadoEn          time.Time `json:"creado_en"`
}

type Contacto struct {
	ID            uuid.UUID `json:"id"`
	Nombre        string    `json:"nombre"`
	Empresa       string    `json:"empresa"`
	Correo        string    `json:"correo"`
	Pais          *string   `json:"pais"`
	CamposExtra   []byte    `json:"campos_extra"`
	CreadoEn      time.Time `json:"creado_en"`
	ActualizadoEn time.Time `json:"actualizado_en"`
}

type ContactoLista struct {
	ContactoID uuid.UUID `json:"contacto_id"`
	ListaID    uuid.UUID `json:"lista_id"`
	AgregadoEn time.Time `json:"agregado_en"`
}

type Correspondencia struct {
	ID            uuid.UUID  `json:"id"`
	UsuarioID     uuid.UUID  `json:"usuario_id"`
	ListaID       *uuid.UUID `json:"lista_id"`
	Asunto        string     `json:"asunto"`
	Cuerpo        string     `json:"cuerpo"`
	Estado        string     `json:"estado"`
	CreadoEn      time.Time  `json:"creado_en"`
	ActualizadoEn time.Time  `json:"actualizado_en"`
}

type Envio struct {
	ID                 uuid.UUID  `json:"id"`
	CorrespondenciaID  uuid.UUID  `json:"correspondencia_id"`
	ContactoID         uuid.UUID  `json:"contacto_id"`
	ProveedorMensajeID *string    `json:"proveedor_mensaje_id"`
	Estado             string     `json:"estado"`
	FechaEnvio         *time.Time `json:"fecha_envio"`
	CreadoEn           time.Time  `json:"creado_en"`
	ActualizadoEn      time.Time  `json:"actualizado_en"`
}

type EventoEnvio struct {
	ID       uuid.UUID `json:"id"`
	EnvioID  uuid.UUID `json:"envio_id"`
	Tipo     string    `json:"tipo"`
	Fecha    time.Time `json:"fecha"`
	Payload  []byte    `json:"payload"`
	CreadoEn time.Time `json:"creado_en"`
}

type ListaContacto struct {
	ID          uuid.UUID `json:"id"`
	Nombre      string    `json:"nombre"`
	Descripcion *string   `json:"descripcion"`
	CreadoEn    time.Time `json:"creado_en"`
}

type Usuario struct {
	ID           uuid.UUID `json:"id"`
	Nombre       string    `json:"nombre"`
	Correo       string    `json:"correo"`
	PasswordHash string    `json:"password_hash"`
	CreadoEn     time.Time `json:"creado_en"`
}
