// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rueda.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const aprobarPublicacion = `-- name: AprobarPublicacion :one
UPDATE rueda_publicacion
SET estado = 'aprobado',
    motivo_rechazo = NULL,
    revisado_en = now()
WHERE id = $1
RETURNING id, empresa_id, tipo, titulo, descripcion, imagen_url, estado, motivo_rechazo, creado_en, revisado_en
`

func (q *Queries) AprobarPublicacion(ctx context.Context, id uuid.UUID) (RuedaPublicacion, error) {
	row := q.db.QueryRow(ctx, aprobarPublicacion, id)
	var i RuedaPublicacion
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Tipo,
		&i.Titulo,
		&i.Descripcion,
		&i.ImagenUrl,
		&i.Estado,
		&i.MotivoRechazo,
		&i.CreadoEn,
		&i.RevisadoEn,
	)
	return i, err
}

const aprobarRuedaEmpresa = `-- name: AprobarRuedaEmpresa :one
UPDATE rueda_empresa
SET estado = 'aprobado',
    contacto_id = $2,
    motivo_rechazo = NULL,
    revisado_en = now()
WHERE id = $1
RETURNING id, razon_social, ruc, persona_encargada, cargo_encargado, correo, direccion, ciudad, region, pais, codigo_postal, telefono, celular, pagina_web, estado, motivo_rechazo, contacto_id, creado_en, revisado_en
`

type AprobarRuedaEmpresaParams struct {
	ID         uuid.UUID  `json:"id"`
	ContactoID *uuid.UUID `json:"contacto_id"`
}

func (q *Queries) AprobarRuedaEmpresa(ctx context.Context, arg AprobarRuedaEmpresaParams) (RuedaEmpresa, error) {
	row := q.db.QueryRow(ctx, aprobarRuedaEmpresa, arg.ID, arg.ContactoID)
	var i RuedaEmpresa
	err := row.Scan(
		&i.ID,
		&i.RazonSocial,
		&i.Ruc,
		&i.PersonaEncargada,
		&i.CargoEncargado,
		&i.Correo,
		&i.Direccion,
		&i.Ciudad,
		&i.Region,
		&i.Pais,
		&i.CodigoPostal,
		&i.Telefono,
		&i.Celular,
		&i.PaginaWeb,
		&i.Estado,
		&i.MotivoRechazo,
		&i.ContactoID,
		&i.CreadoEn,
		&i.RevisadoEn,
	)
	return i, err
}

const contarPublicaciones = `-- name: ContarPublicaciones :one
SELECT count(*) FROM rueda_publicacion p
WHERE ($1::text IS NULL OR p.estado = $1::text)
  AND ($2::text IS NULL OR p.tipo = $2::text)
`

type ContarPublicacionesParams struct {
	Estado *string `json:"estado"`
	Tipo   *string `json:"tipo"`
}

func (q *Queries) ContarPublicaciones(ctx context.Context, arg ContarPublicacionesParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarPublicaciones, arg.Estado, arg.Tipo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarRuedaEmpresas = `-- name: ContarRuedaEmpresas :one
SELECT count(*) FROM rueda_empresa
WHERE ($1::text IS NULL OR estado = $1::text)
`

func (q *Queries) ContarRuedaEmpresas(ctx context.Context, estado *string) (int64, error) {
	row := q.db.QueryRow(ctx, contarRuedaEmpresas, estado)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearPublicacion = `-- name: CrearPublicacion :one
INSERT INTO rueda_publicacion (empresa_id, tipo, titulo, descripcion, imagen_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, empresa_id, tipo, titulo, descripcion, imagen_url, estado, motivo_rechazo, creado_en, revisado_en
`

type CrearPublicacionParams struct {
	EmpresaID   uuid.UUID `json:"empresa_id"`
	Tipo        string    `json:"tipo"`
	Titulo      string    `json:"titulo"`
	Descripcion string    `json:"descripcion"`
	ImagenUrl   *string   `json:"imagen_url"`
}

func (q *Queries) CrearPublicacion(ctx context.Context, arg CrearPublicacionParams) (RuedaPublicacion, error) {
	row := q.db.QueryRow(ctx, crearPublicacion,
		arg.EmpresaID,
		arg.Tipo,
		arg.Titulo,
		arg.Descripcion,
		arg.ImagenUrl,
	)
	var i RuedaPublicacion
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Tipo,
		&i.Titulo,
		&i.Descripcion,
		&i.ImagenUrl,
		&i.Estado,
		&i.MotivoRechazo,
		&i.CreadoEn,
		&i.RevisadoEn,
	)
	return i, err
}

const guardarCoincidencia = `-- name: GuardarCoincidencia :exec
INSERT INTO rueda_coincidencia (demanda_id, oferta_id, puntaje, motivo)
VALUES ($1, $2, $3, $4)
ON CONFLICT (demanda_id, oferta_id) DO UPDATE
SET puntaje = EXCLUDED.puntaje,
    motivo = EXCLUDED.motivo
`

type GuardarCoincidenciaParams struct {
	DemandaID uuid.UUID `json:"demanda_id"`
	OfertaID  uuid.UUID `json:"oferta_id"`
	Puntaje   int32     `json:"puntaje"`
	Motivo    string    `json:"motivo"`
}

func (q *Queries) GuardarCoincidencia(ctx context.Context, arg GuardarCoincidenciaParams) error {
	_, err := q.db.Exec(ctx, guardarCoincidencia,
		arg.DemandaID,
		arg.OfertaID,
		arg.Puntaje,
		arg.Motivo,
	)
	return err
}

const listarCandidatas = `-- name: ListarCandidatas :many
SELECT p.id, p.titulo, p.descripcion,
    e.razon_social, e.ciudad AS empresa_ciudad, e.pais AS empresa_pais
FROM rueda_publicacion p
JOIN rueda_empresa e ON e.id = p.empresa_id
WHERE p.estado = 'aprobado'
  AND e.estado = 'aprobado'
  AND p.tipo = $1
  AND p.empresa_id <> $2
ORDER BY p.creado_en DESC
LIMIT 60
`

type ListarCandidatasParams struct {
	Tipo      string    `json:"tipo"`
	EmpresaID uuid.UUID `json:"empresa_id"`
}

type ListarCandidatasRow struct {
	ID            uuid.UUID `json:"id"`
	Titulo        string    `json:"titulo"`
	Descripcion   string    `json:"descripcion"`
	RazonSocial   string    `json:"razon_social"`
	EmpresaCiudad *string   `json:"empresa_ciudad"`
	EmpresaPais   string    `json:"empresa_pais"`
}

func (q *Queries) ListarCandidatas(ctx context.Context, arg ListarCandidatasParams) ([]ListarCandidatasRow, error) {
	rows, err := q.db.Query(ctx, listarCandidatas, arg.Tipo, arg.EmpresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarCandidatasRow{}
	for rows.Next() {
		var i ListarCandidatasRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.RazonSocial,
			&i.EmpresaCiudad,
			&i.EmpresaPais,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarCoincidencias = `-- name: ListarCoincidencias :many
SELECT c.id, c.demanda_id, c.oferta_id, c.puntaje, c.motivo, c.estado, c.creado_en, c.notificada_en,
    d.titulo AS demanda_titulo, de.razon_social AS demanda_empresa, de.correo AS demanda_correo,
    o.titulo AS oferta_titulo, oe.razon_social AS oferta_empresa, oe.correo AS oferta_correo
FROM rueda_coincidencia c
JOIN rueda_publicacion d ON d.id = c.demanda_id
JOIN rueda_empresa de ON de.id = d.empresa_id
JOIN rueda_publicacion o ON o.id = c.oferta_id
JOIN rueda_empresa oe ON oe.id = o.empresa_id
WHERE ($1::text IS NULL OR c.estado = $1::text)
ORDER BY c.puntaje DESC, c.creado_en DESC
LIMIT 200
`

type ListarCoincidenciasRow struct {
	ID             uuid.UUID  `json:"id"`
	DemandaID      uuid.UUID  `json:"demanda_id"`
	OfertaID       uuid.UUID  `json:"oferta_id"`
	Puntaje        int32      `json:"puntaje"`
	Motivo         string     `json:"motivo"`
	Estado         string     `json:"estado"`
	CreadoEn       time.Time  `json:"creado_en"`
	NotificadaEn   *time.Time `json:"notificada_en"`
	DemandaTitulo  string     `json:"demanda_titulo"`
	DemandaEmpresa string     `json:"demanda_empresa"`
	DemandaCorreo  string     `json:"demanda_correo"`
	OfertaTitulo   string     `json:"oferta_titulo"`
	OfertaEmpresa  string     `json:"oferta_empresa"`
	OfertaCorreo   string     `json:"oferta_correo"`
}

func (q *Queries) ListarCoincidencias(ctx context.Context, estado *string) ([]ListarCoincidenciasRow, error) {
	rows, err := q.db.Query(ctx, listarCoincidencias, estado)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarCoincidenciasRow{}
	for rows.Next() {
		var i ListarCoincidenciasRow
		if err := rows.Scan(
			&i.ID,
			&i.DemandaID,
			&i.OfertaID,
			&i.Puntaje,
			&i.Motivo,
			&i.Estado,
			&i.CreadoEn,
			&i.NotificadaEn,
			&i.DemandaTitulo,
			&i.DemandaEmpresa,
			&i.DemandaCorreo,
			&i.OfertaTitulo,
			&i.OfertaEmpresa,
			&i.OfertaCorreo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPublicaciones = `-- name: ListarPublicaciones :many
SELECT p.id, p.empresa_id, p.tipo, p.titulo, p.descripcion, p.imagen_url, p.estado, p.motivo_rechazo, p.creado_en, p.revisado_en,
    e.razon_social, e.ciudad AS empresa_ciudad, e.pais AS empresa_pais,
    e.correo AS empresa_correo, e.estado AS empresa_estado
FROM rueda_publicacion p
JOIN rueda_empresa e ON e.id = p.empresa_id
WHERE ($3::text IS NULL OR p.estado = $3::text)
  AND ($4::text IS NULL OR p.tipo = $4::text)
ORDER BY p.creado_en DESC
LIMIT $1 OFFSET $2
`

type ListarPublicacionesParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Estado *string `json:"estado"`
	Tipo   *string `json:"tipo"`
}

type ListarPublicacionesRow struct {
	ID            uuid.UUID  `json:"id"`
	EmpresaID     uuid.UUID  `json:"empresa_id"`
	Tipo          string     `json:"tipo"`
	Titulo        string     `json:"titulo"`
	Descripcion   string     `json:"descripcion"`
	ImagenUrl     *string    `json:"imagen_url"`
	Estado        string     `json:"estado"`
	MotivoRechazo *string    `json:"motivo_rechazo"`
	CreadoEn      time.Time  `json:"creado_en"`
	RevisadoEn    *time.Time `json:"revisado_en"`
	RazonSocial   string     `json:"razon_social"`
	EmpresaCiudad *string    `json:"empresa_ciudad"`
	EmpresaPais   string     `json:"empresa_pais"`
	EmpresaCorreo string     `json:"empresa_correo"`
	EmpresaEstado string     `json:"empresa_estado"`
}

func (q *Queries) ListarPublicaciones(ctx context.Context, arg ListarPublicacionesParams) ([]ListarPublicacionesRow, error) {
	rows, err := q.db.Query(ctx, listarPublicaciones,
		arg.Limit,
		arg.Offset,
		arg.Estado,
		arg.Tipo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarPublicacionesRow{}
	for rows.Next() {
		var i ListarPublicacionesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Tipo,
			&i.Titulo,
			&i.Descripcion,
			&i.ImagenUrl,
			&i.Estado,
			&i.MotivoRechazo,
			&i.CreadoEn,
			&i.RevisadoEn,
			&i.RazonSocial,
			&i.EmpresaCiudad,
			&i.EmpresaPais,
			&i.EmpresaCorreo,
			&i.EmpresaEstado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPublicacionesPublicas = `-- name: ListarPublicacionesPublicas :many
SELECT p.id, p.tipo, p.titulo, p.descripcion, p.imagen_url, p.creado_en,
    e.razon_social, e.ciudad AS empresa_ciudad, e.pais AS empresa_pais
FROM rueda_publicacion p
JOIN rueda_empresa e ON e.id = p.empresa_id
WHERE p.estado = 'aprobado'
  AND e.estado = 'aprobado'
  AND ($1::text IS NULL OR p.tipo = $1::text)
ORDER BY p.creado_en DESC
LIMIT 200
`

type ListarPublicacionesPublicasRow struct {
	ID            uuid.UUID `json:"id"`
	Tipo          string    `json:"tipo"`
	Titulo        string    `json:"titulo"`
	Descripcion   string    `json:"descripcion"`
	ImagenUrl     *string   `json:"imagen_url"`
	CreadoEn      time.Time `json:"creado_en"`
	RazonSocial   string    `json:"razon_social"`
	EmpresaCiudad *string   `json:"empresa_ciudad"`
	EmpresaPais   string    `json:"empresa_pais"`
}

func (q *Queries) ListarPublicacionesPublicas(ctx context.Context, tipo *string) ([]ListarPublicacionesPublicasRow, error) {
	rows, err := q.db.Query(ctx, listarPublicacionesPublicas, tipo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarPublicacionesPublicasRow{}
	for rows.Next() {
		var i ListarPublicacionesPublicasRow
		if err := rows.Scan(
			&i.ID,
			&i.Tipo,
			&i.Titulo,
			&i.Descripcion,
			&i.ImagenUrl,
			&i.CreadoEn,
			&i.RazonSocial,
			&i.EmpresaCiudad,
			&i.EmpresaPais,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarRuedaEmpresas = `-- name: ListarRuedaEmpresas :many
SELECT e.id, e.razon_social, e.ruc, e.persona_encargada, e.cargo_encargado, e.correo, e.direccion, e.ciudad, e.region, e.pais, e.codigo_postal, e.telefono, e.celular, e.pagina_web, e.estado, e.motivo_rechazo, e.contacto_id, e.creado_en, e.revisado_en,
    (SELECT count(*) FROM rueda_publicacion p WHERE p.empresa_id = e.id) AS publicaciones
FROM rueda_empresa e
WHERE ($3::text IS NULL OR e.estado = $3::text)
ORDER BY e.creado_en DESC
LIMIT $1 OFFSET $2
`

type ListarRuedaEmpresasParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Estado *string `json:"estado"`
}

type ListarRuedaEmpresasRow struct {
	ID               uuid.UUID  `json:"id"`
	RazonSocial      string     `json:"razon_social"`
	Ruc              string     `json:"ruc"`
	PersonaEncargada string     `json:"persona_encargada"`
	CargoEncargado   *string    `json:"cargo_encargado"`
	Correo           string     `json:"correo"`
	Direccion        *string    `json:"direccion"`
	Ciudad           *string    `json:"ciudad"`
	Region           *string    `json:"region"`
	Pais             string     `json:"pais"`
	CodigoPostal     *string    `json:"codigo_postal"`
	Telefono         *string    `json:"telefono"`
	Celular          *string    `json:"celular"`
	PaginaWeb        *string    `json:"pagina_web"`
	Estado           string     `json:"estado"`
	MotivoRechazo    *string    `json:"motivo_rechazo"`
	ContactoID       *uuid.UUID `json:"contacto_id"`
	CreadoEn         time.Time  `json:"creado_en"`
	RevisadoEn       *time.Time `json:"revisado_en"`
	Publicaciones    int64      `json:"publicaciones"`
}

func (q *Queries) ListarRuedaEmpresas(ctx context.Context, arg ListarRuedaEmpresasParams) ([]ListarRuedaEmpresasRow, error) {
	rows, err := q.db.Query(ctx, listarRuedaEmpresas, arg.Limit, arg.Offset, arg.Estado)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListarRuedaEmpresasRow{}
	for rows.Next() {
		var i ListarRuedaEmpresasRow
		if err := rows.Scan(
			&i.ID,
			&i.RazonSocial,
			&i.Ruc,
			&i.PersonaEncargada,
			&i.CargoEncargado,
			&i.Correo,
			&i.Direccion,
			&i.Ciudad,
			&i.Region,
			&i.Pais,
			&i.CodigoPostal,
			&i.Telefono,
			&i.Celular,
			&i.PaginaWeb,
			&i.Estado,
			&i.MotivoRechazo,
			&i.ContactoID,
			&i.CreadoEn,
			&i.RevisadoEn,
			&i.Publicaciones,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarCoincidencia = `-- name: MarcarCoincidencia :one
UPDATE rueda_coincidencia
SET estado = $1::text,
    notificada_en = CASE
        WHEN $1::text = 'notificada' THEN now()
        ELSE notificada_en
    END
WHERE id = $2
RETURNING id, demanda_id, oferta_id, puntaje, motivo, estado, creado_en, notificada_en
`

type MarcarCoincidenciaParams struct {
	Estado string    `json:"estado"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) MarcarCoincidencia(ctx context.Context, arg MarcarCoincidenciaParams) (RuedaCoincidencia, error) {
	row := q.db.QueryRow(ctx, marcarCoincidencia, arg.Estado, arg.ID)
	var i RuedaCoincidencia
	err := row.Scan(
		&i.ID,
		&i.DemandaID,
		&i.OfertaID,
		&i.Puntaje,
		&i.Motivo,
		&i.Estado,
		&i.CreadoEn,
		&i.NotificadaEn,
	)
	return i, err
}

const obtenerCoincidencia = `-- name: ObtenerCoincidencia :one
SELECT c.id, c.demanda_id, c.oferta_id, c.puntaje, c.motivo, c.estado, c.creado_en, c.notificada_en,
    d.titulo AS demanda_titulo, d.descripcion AS demanda_descripcion,
    de.razon_social AS demanda_empresa, de.correo AS demanda_correo,
    de.persona_encargada AS demanda_encargado,
    o.titulo AS oferta_titulo, o.descripcion AS oferta_descripcion,
    oe.razon_social AS oferta_empresa, oe.correo AS oferta_correo,
    oe.persona_encargada AS oferta_encargado
FROM rueda_coincidencia c
JOIN rueda_publicacion d ON d.id = c.demanda_id
JOIN rueda_empresa de ON de.id = d.empresa_id
JOIN rueda_publicacion o ON o.id = c.oferta_id
JOIN rueda_empresa oe ON oe.id = o.empresa_id
WHERE c.id = $1
`

type ObtenerCoincidenciaRow struct {
	ID                 uuid.UUID  `json:"id"`
	DemandaID          uuid.UUID  `json:"demanda_id"`
	OfertaID           uuid.UUID  `json:"oferta_id"`
	Puntaje            int32      `json:"puntaje"`
	Motivo             string     `json:"motivo"`
	Estado             string     `json:"estado"`
	CreadoEn           time.Time  `json:"creado_en"`
	NotificadaEn       *time.Time `json:"notificada_en"`
	DemandaTitulo      string     `json:"demanda_titulo"`
	DemandaDescripcion string     `json:"demanda_descripcion"`
	DemandaEmpresa     string     `json:"demanda_empresa"`
	DemandaCorreo      string     `json:"demanda_correo"`
	DemandaEncargado   string     `json:"demanda_encargado"`
	OfertaTitulo       string     `json:"oferta_titulo"`
	OfertaDescripcion  string     `json:"oferta_descripcion"`
	OfertaEmpresa      string     `json:"oferta_empresa"`
	OfertaCorreo       string     `json:"oferta_correo"`
	OfertaEncargado    string     `json:"oferta_encargado"`
}

func (q *Queries) ObtenerCoincidencia(ctx context.Context, id uuid.UUID) (ObtenerCoincidenciaRow, error) {
	row := q.db.QueryRow(ctx, obtenerCoincidencia, id)
	var i ObtenerCoincidenciaRow
	err := row.Scan(
		&i.ID,
		&i.DemandaID,
		&i.OfertaID,
		&i.Puntaje,
		&i.Motivo,
		&i.Estado,
		&i.CreadoEn,
		&i.NotificadaEn,
		&i.DemandaTitulo,
		&i.DemandaDescripcion,
		&i.DemandaEmpresa,
		&i.DemandaCorreo,
		&i.DemandaEncargado,
		&i.OfertaTitulo,
		&i.OfertaDescripcion,
		&i.OfertaEmpresa,
		&i.OfertaCorreo,
		&i.OfertaEncargado,
	)
	return i, err
}

const obtenerPublicacion = `-- name: ObtenerPublicacion :one
SELECT p.id, p.empresa_id, p.tipo, p.titulo, p.descripcion, p.imagen_url, p.estado, p.motivo_rechazo, p.creado_en, p.revisado_en,
    e.razon_social, e.ciudad AS empresa_ciudad, e.pais AS empresa_pais,
    e.correo AS empresa_correo, e.estado AS empresa_estado
FROM rueda_publicacion p
JOIN rueda_empresa e ON e.id = p.empresa_id
WHERE p.id = $1
`

type ObtenerPublicacionRow struct {
	ID            uuid.UUID  `json:"id"`
	EmpresaID     uuid.UUID  `json:"empresa_id"`
	Tipo          string     `json:"tipo"`
	Titulo        string     `json:"titulo"`
	Descripcion   string     `json:"descripcion"`
	ImagenUrl     *string    `json:"imagen_url"`
	Estado        string     `json:"estado"`
	MotivoRechazo *string    `json:"motivo_rechazo"`
	CreadoEn      time.Time  `json:"creado_en"`
	RevisadoEn    *time.Time `json:"revisado_en"`
	RazonSocial   string     `json:"razon_social"`
	EmpresaCiudad *string    `json:"empresa_ciudad"`
	EmpresaPais   string     `json:"empresa_pais"`
	EmpresaCorreo string     `json:"empresa_correo"`
	EmpresaEstado string     `json:"empresa_estado"`
}

func (q *Queries) ObtenerPublicacion(ctx context.Context, id uuid.UUID) (ObtenerPublicacionRow, error) {
	row := q.db.QueryRow(ctx, obtenerPublicacion, id)
	var i ObtenerPublicacionRow
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Tipo,
		&i.Titulo,
		&i.Descripcion,
		&i.ImagenUrl,
		&i.Estado,
		&i.MotivoRechazo,
		&i.CreadoEn,
		&i.RevisadoEn,
		&i.RazonSocial,
		&i.EmpresaCiudad,
		&i.EmpresaPais,
		&i.EmpresaCorreo,
		&i.EmpresaEstado,
	)
	return i, err
}

const obtenerRuedaEmpresa = `-- name: ObtenerRuedaEmpresa :one
SELECT id, razon_social, ruc, persona_encargada, cargo_encargado, correo, direccion, ciudad, region, pais, codigo_postal, telefono, celular, pagina_web, estado, motivo_rechazo, contacto_id, creado_en, revisado_en FROM rueda_empresa WHERE id = $1
`

func (q *Queries) ObtenerRuedaEmpresa(ctx context.Context, id uuid.UUID) (RuedaEmpresa, error) {
	row := q.db.QueryRow(ctx, obtenerRuedaEmpresa, id)
	var i RuedaEmpresa
	err := row.Scan(
		&i.ID,
		&i.RazonSocial,
		&i.Ruc,
		&i.PersonaEncargada,
		&i.CargoEncargado,
		&i.Correo,
		&i.Direccion,
		&i.Ciudad,
		&i.Region,
		&i.Pais,
		&i.CodigoPostal,
		&i.Telefono,
		&i.Celular,
		&i.PaginaWeb,
		&i.Estado,
		&i.MotivoRechazo,
		&i.ContactoID,
		&i.CreadoEn,
		&i.RevisadoEn,
	)
	return i, err
}

const rechazarPublicacion = `-- name: RechazarPublicacion :one
UPDATE rueda_publicacion
SET estado = 'rechazado',
    motivo_rechazo = $2,
    revisado_en = now()
WHERE id = $1
RETURNING id, empresa_id, tipo, titulo, descripcion, imagen_url, estado, motivo_rechazo, creado_en, revisado_en
`

type RechazarPublicacionParams struct {
	ID            uuid.UUID `json:"id"`
	MotivoRechazo *string   `json:"motivo_rechazo"`
}

func (q *Queries) RechazarPublicacion(ctx context.Context, arg RechazarPublicacionParams) (RuedaPublicacion, error) {
	row := q.db.QueryRow(ctx, rechazarPublicacion, arg.ID, arg.MotivoRechazo)
	var i RuedaPublicacion
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Tipo,
		&i.Titulo,
		&i.Descripcion,
		&i.ImagenUrl,
		&i.Estado,
		&i.MotivoRechazo,
		&i.CreadoEn,
		&i.RevisadoEn,
	)
	return i, err
}

const rechazarRuedaEmpresa = `-- name: RechazarRuedaEmpresa :one
UPDATE rueda_empresa
SET estado = 'rechazado',
    motivo_rechazo = $2,
    revisado_en = now()
WHERE id = $1
RETURNING id, razon_social, ruc, persona_encargada, cargo_encargado, correo, direccion, ciudad, region, pais, codigo_postal, telefono, celular, pagina_web, estado, motivo_rechazo, contacto_id, creado_en, revisado_en
`

type RechazarRuedaEmpresaParams struct {
	ID            uuid.UUID `json:"id"`
	MotivoRechazo *string   `json:"motivo_rechazo"`
}

func (q *Queries) RechazarRuedaEmpresa(ctx context.Context, arg RechazarRuedaEmpresaParams) (RuedaEmpresa, error) {
	row := q.db.QueryRow(ctx, rechazarRuedaEmpresa, arg.ID, arg.MotivoRechazo)
	var i RuedaEmpresa
	err := row.Scan(
		&i.ID,
		&i.RazonSocial,
		&i.Ruc,
		&i.PersonaEncargada,
		&i.CargoEncargado,
		&i.Correo,
		&i.Direccion,
		&i.Ciudad,
		&i.Region,
		&i.Pais,
		&i.CodigoPostal,
		&i.Telefono,
		&i.Celular,
		&i.PaginaWeb,
		&i.Estado,
		&i.MotivoRechazo,
		&i.ContactoID,
		&i.CreadoEn,
		&i.RevisadoEn,
	)
	return i, err
}

const registrarRuedaEmpresa = `-- name: RegistrarRuedaEmpresa :one
INSERT INTO rueda_empresa (
    razon_social, ruc, persona_encargada, cargo_encargado, correo, direccion,
    ciudad, region, pais, codigo_postal, telefono, celular, pagina_web
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (correo) DO UPDATE SET correo = EXCLUDED.correo
RETURNING id, razon_social, ruc, persona_encargada, cargo_encargado, correo, direccion, ciudad, region, pais, codigo_postal, telefono, celular, pagina_web, estado, motivo_rechazo, contacto_id, creado_en, revisado_en
`

type RegistrarRuedaEmpresaParams struct {
	RazonSocial      string  `json:"razon_social"`
	Ruc              string  `json:"ruc"`
	PersonaEncargada string  `json:"persona_encargada"`
	CargoEncargado   *string `json:"cargo_encargado"`
	Correo           string  `json:"correo"`
	Direccion        *string `json:"direccion"`
	Ciudad           *string `json:"ciudad"`
	Region           *string `json:"region"`
	Pais             string  `json:"pais"`
	CodigoPostal     *string `json:"codigo_postal"`
	Telefono         *string `json:"telefono"`
	Celular          *string `json:"celular"`
	PaginaWeb        *string `json:"pagina_web"`
}

func (q *Queries) RegistrarRuedaEmpresa(ctx context.Context, arg RegistrarRuedaEmpresaParams) (RuedaEmpresa, error) {
	row := q.db.QueryRow(ctx, registrarRuedaEmpresa,
		arg.RazonSocial,
		arg.Ruc,
		arg.PersonaEncargada,
		arg.CargoEncargado,
		arg.Correo,
		arg.Direccion,
		arg.Ciudad,
		arg.Region,
		arg.Pais,
		arg.CodigoPostal,
		arg.Telefono,
		arg.Celular,
		arg.PaginaWeb,
	)
	var i RuedaEmpresa
	err := row.Scan(
		&i.ID,
		&i.RazonSocial,
		&i.Ruc,
		&i.PersonaEncargada,
		&i.CargoEncargado,
		&i.Correo,
		&i.Direccion,
		&i.Ciudad,
		&i.Region,
		&i.Pais,
		&i.CodigoPostal,
		&i.Telefono,
		&i.Celular,
		&i.PaginaWeb,
		&i.Estado,
		&i.MotivoRechazo,
		&i.ContactoID,
		&i.CreadoEn,
		&i.RevisadoEn,
	)
	return i, err
}
