// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supresion.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const contarSuprimidos = `-- name: ContarSuprimidos :one
SELECT count(*) FROM supresion
`

func (q *Queries) ContarSuprimidos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarSuprimidos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const estaSuprimido = `-- name: EstaSuprimido :one
SELECT EXISTS (SELECT 1 FROM supresion WHERE correo = $1)
`

func (q *Queries) EstaSuprimido(ctx context.Context, correo string) (bool, error) {
	row := q.db.QueryRow(ctx, estaSuprimido, correo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listarSuprimidos = `-- name: ListarSuprimidos :many
SELECT correo, motivo, detalle, creado_en FROM supresion ORDER BY creado_en DESC LIMIT $1 OFFSET $2
`

type ListarSuprimidosParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListarSuprimidos(ctx context.Context, arg ListarSuprimidosParams) ([]Supresion, error) {
	rows, err := q.db.Query(ctx, listarSuprimidos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supresion{}
	for rows.Next() {
		var i Supresion
		if err := rows.Scan(
			&i.Correo,
			&i.Motivo,
			&i.Detalle,
			&i.CreadoEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerContactoPorID = `-- name: ObtenerContactoPorID :one
SELECT id, nombre, empresa, correo, pais, campos_extra, creado_en, actualizado_en FROM contacto WHERE id = $1
`

func (q *Queries) ObtenerContactoPorID(ctx context.Context, id uuid.UUID) (Contacto, error) {
	row := q.db.QueryRow(ctx, obtenerContactoPorID, id)
	var i Contacto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Empresa,
		&i.Correo,
		&i.Pais,
		&i.CamposExtra,
		&i.CreadoEn,
		&i.ActualizadoEn,
	)
	return i, err
}

const quitarSupresion = `-- name: QuitarSupresion :execrows
DELETE FROM supresion WHERE correo = $1
`

func (q *Queries) QuitarSupresion(ctx context.Context, correo string) (int64, error) {
	result, err := q.db.Exec(ctx, quitarSupresion, correo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suprimirCorreo = `-- name: SuprimirCorreo :exec
INSERT INTO supresion (correo, motivo, detalle)
VALUES ($1, $2, $3)
ON CONFLICT (correo) DO UPDATE
SET motivo = EXCLUDED.motivo,
    detalle = EXCLUDED.detalle
`

type SuprimirCorreoParams struct {
	Correo  string  `json:"correo"`
	Motivo  string  `json:"motivo"`
	Detalle *string `json:"detalle"`
}

func (q *Queries) SuprimirCorreo(ctx context.Context, arg SuprimirCorreoParams) error {
	_, err := q.db.Exec(ctx, suprimirCorreo, arg.Correo, arg.Motivo, arg.Detalle)
	return err
}

const suprimirPorEnvio = `-- name: SuprimirPorEnvio :exec
INSERT INTO supresion (correo, motivo, detalle)
SELECT c.correo, $2, $3
FROM envio e
JOIN contacto c ON c.id = e.contacto_id
WHERE e.id = $1
ON CONFLICT (correo) DO UPDATE
SET motivo = EXCLUDED.motivo,
    detalle = EXCLUDED.detalle
`

type SuprimirPorEnvioParams struct {
	ID      uuid.UUID `json:"id"`
	Motivo  string    `json:"motivo"`
	Detalle *string   `json:"detalle"`
}

func (q *Queries) SuprimirPorEnvio(ctx context.Context, arg SuprimirPorEnvioParams) error {
	_, err := q.db.Exec(ctx, suprimirPorEnvio, arg.ID, arg.Motivo, arg.Detalle)
	return err
}
