// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const contarUsuarios = `-- name: ContarUsuarios :one
SELECT count(*) FROM usuario
`

func (q *Queries) ContarUsuarios(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarUsuarios)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearUsuario = `-- name: CrearUsuario :one
INSERT INTO usuario (nombre, correo, password_hash)
VALUES ($1, $2, $3)
RETURNING id, nombre, correo, password_hash, creado_en
`

type CrearUsuarioParams struct {
	Nombre       string `json:"nombre"`
	Correo       string `json:"correo"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, crearUsuario, arg.Nombre, arg.Correo, arg.PasswordHash)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Correo,
		&i.PasswordHash,
		&i.CreadoEn,
	)
	return i, err
}

const obtenerUsuario = `-- name: ObtenerUsuario :one
SELECT id, nombre, correo, password_hash, creado_en FROM usuario WHERE id = $1
`

func (q *Queries) ObtenerUsuario(ctx context.Context, id uuid.UUID) (Usuario, error) {
	row := q.db.QueryRow(ctx, obtenerUsuario, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Correo,
		&i.PasswordHash,
		&i.CreadoEn,
	)
	return i, err
}

const obtenerUsuarioPorCorreo = `-- name: ObtenerUsuarioPorCorreo :one
SELECT id, nombre, correo, password_hash, creado_en FROM usuario WHERE correo = $1
`

func (q *Queries) ObtenerUsuarioPorCorreo(ctx context.Context, correo string) (Usuario, error) {
	row := q.db.QueryRow(ctx, obtenerUsuarioPorCorreo, correo)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Correo,
		&i.PasswordHash,
		&i.CreadoEn,
	)
	return i, err
}
